[package]
name = "test-lambda"
version = "0.1.0"
authors = ["toidiu <apoorv@toidiu.com>"]
edition = "2018"

[dependencies]
serde = "^1"
serde_derive = "^1"
simple_logger = "^1"
lambda_runtime = "^0.1"
log = "^0.4"
